### ISSUE TITLE
API v2 support

### ISSUE THREAD

**Issue by ibo549** [mstarzec386/MMM-Airly#11]
With their API v2, it's now possible to acquire a legit API key. 
I signed-up as a dev and got one. Re-cloned this repo, did npm install and tried running it with my new API key.
It got stuck on Loading Air Quality data screen. Seems like v2 API isn't supported? 
Are you planning to add support for the new API? If it's an ongoing work, it would be great if you add this to readme. If there is no ongoing work, I am happy to add support for Airli v2 API.

<img width="398" alt="Screenshot 2020-05-27 at 23 50 45" src="https://user-images.githubusercontent.com/1646505/83075907-e8c38680-a074-11ea-9ef8-707db4b68308.png">

**Comment by ibo549** [comment]
I am receiving 401 when trying to retrieve data from the API. Seems like either, my API key hasn't been approved yet or they don't allow fetching such data to public API keys. If that's the case, I assume we gotta go back to fun steal their API key on their web app? 🥇 
<img width="204" alt="Screenshot 2020-05-27 at 23 57 12" src="https://user-images.githubusercontent.com/1646505/83076428-ce3ddd00-a075-11ea-8f82-6cb021f6e8ed.png">

**Comment by ibo549** [comment]
It was about wrong API key. It all works now. Thanks!
<img width="277" alt="Screenshot 2020-05-28 at 00 10 47" src="https://user-images.githubusercontent.com/1646505/83077454-b49d9500-a077-11ea-920a-d6dc0353e797.png">

**Comment by mstarzec386** [comment]
I'm glad it works without my help 😂
