### ISSUE TITLE
zmiana URLi Airly

### ISSUE THREAD

**Issue by Santanachia** [mstarzec386/MMM-Airly#6]
Hej,
w Read.me napisałeś jak zdobyć SensorID. niestety zmieniły się adresy i teraz zamiast
[map.airly.eu/pl/...&id=2878](https://map.airly.eu/pl/#latitude=49.69678&longitude=18.99732&id=2878) jest [airly.eu/map/pl/...,i3321](https://airly.eu/map/pl/#49.69678,18.99732,i3321)... jak widać, zmieniła się nie tylko struktura ale również numer :/

**Comment by mstarzec386** [comment]
wiem ze wiecznosc to trwalo ale dodalem support api v2.
niestety nie zaktualizowalem readme
