### ISSUE TITLE
SensorID Depreciated in latest API

### ISSUE THREAD

**Issue by prodigerati** [mstarzec386/MMM-Airly#9]
Airly Docs info:
https://developer.airly.eu/docs#general.compatibility

In the previous API version we were dealing with a concept of a sensor. You could e.g. query what sensors are present in a given area, and then query each individual sensor for its measurements by the sensorId. Unfortunately such approach can lead to some problems. Our devices fleet is constantly growing and it is inevitable that at some point particular device will have to be replaced or moved to another location. When that happens, querying for data by sensorId can lead to incorrect results, since you would be querying for a device that was in fact removed, or replaced.

In the new API version we solve this problem by introducing a concept of installation. An installation is an entity that binds together a sensor and its location where it's installed at a particular time. Thus you can always query an installation safely without risking you would be querying incorrect sensor.

Any plans to allow for an installation?

**Comment by mstarzec386** [comment]
fixed.
Now supports API v2
